/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantCheckIn.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantCheckIn (0 custom class methods, 4 custom properties)

#import "GTLShoppingAssistantCheckIn.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantCheckIn
//

@implementation GTLShoppingAssistantCheckIn
@dynamic checkInDate, key, placeId, userEmail;
@end
