/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantPlaceInfoCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantPlaceInfoCollection (0 custom class methods, 1 custom properties)

#import "GTLShoppingAssistantPlaceInfoCollection.h"

#import "GTLShoppingAssistantPlaceInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantPlaceInfoCollection
//

@implementation GTLShoppingAssistantPlaceInfoCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLShoppingAssistantPlaceInfo class]
                                forKey:@"items"];
  return map;
}

@end
