/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantPlace.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantPlace (0 custom class methods, 4 custom properties)

#import "GTLShoppingAssistantPlace.h"

#import "GTLShoppingAssistantGeoPt.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantPlace
//

@implementation GTLShoppingAssistantPlace
@dynamic address, location, name, placeId;
@end
