/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantCollectionResponseRegistrationRecord.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantCollectionResponseRegistrationRecord (0 custom class methods, 2 custom properties)

#import "GTLShoppingAssistantCollectionResponseRegistrationRecord.h"

#import "GTLShoppingAssistantRegistrationRecord.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantCollectionResponseRegistrationRecord
//

@implementation GTLShoppingAssistantCollectionResponseRegistrationRecord
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLShoppingAssistantRegistrationRecord class]
                                forKey:@"items"];
  return map;
}

@end
