/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistant_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API

#import "GTLShoppingAssistantConstants.m"

#import "GTLShoppingAssistantCheckIn.m"
#import "GTLShoppingAssistantCheckInCollection.m"
#import "GTLShoppingAssistantCollectionResponseRegistration.m"
#import "GTLShoppingAssistantGeoPt.m"
#import "GTLShoppingAssistantJsonMap.m"
#import "GTLShoppingAssistantOffer.m"
#import "GTLShoppingAssistantOfferCollection.m"
#import "GTLShoppingAssistantPlace.m"
#import "GTLShoppingAssistantPlaceInfo.m"
#import "GTLShoppingAssistantPlaceInfoCollection.m"
#import "GTLShoppingAssistantRecommendation.m"
#import "GTLShoppingAssistantRecommendationCollection.m"
#import "GTLShoppingAssistantRegistration.m"

#import "GTLQueryShoppingAssistant.m"
#import "GTLServiceShoppingAssistant.m"
