/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantPlaceInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantPlaceInfo (0 custom class methods, 5 custom properties)

#import "GTLShoppingAssistantPlaceInfo.h"

#import "GTLShoppingAssistantGeoPt.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantPlaceInfo
//

@implementation GTLShoppingAssistantPlaceInfo
@dynamic address, distanceInKilometers, location, name, placeId;
@end
