/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantGeoPt.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantGeoPt (0 custom class methods, 2 custom properties)

#import "GTLShoppingAssistantGeoPt.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantGeoPt
//

@implementation GTLShoppingAssistantGeoPt
@dynamic latitude, longitude;
@end
