/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantCollectionResponseRegistration.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantCollectionResponseRegistration (0 custom class methods, 2 custom properties)

#import "GTLShoppingAssistantCollectionResponseRegistration.h"

#import "GTLShoppingAssistantRegistration.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantCollectionResponseRegistration
//

@implementation GTLShoppingAssistantCollectionResponseRegistration
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLShoppingAssistantRegistration class]
                                forKey:@"items"];
  return map;
}

@end
