/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistant.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API

#import "GTLShoppingAssistantConstants.h"

#import "GTLShoppingAssistantCheckIn.h"
#import "GTLShoppingAssistantCheckInCollection.h"
#import "GTLShoppingAssistantCollectionResponseRegistration.h"
#import "GTLShoppingAssistantGeoPt.h"
#import "GTLShoppingAssistantJsonMap.h"
#import "GTLShoppingAssistantOffer.h"
#import "GTLShoppingAssistantOfferCollection.h"
#import "GTLShoppingAssistantPlace.h"
#import "GTLShoppingAssistantPlaceInfo.h"
#import "GTLShoppingAssistantPlaceInfoCollection.h"
#import "GTLShoppingAssistantRecommendation.h"
#import "GTLShoppingAssistantRecommendationCollection.h"
#import "GTLShoppingAssistantRegistration.h"

#import "GTLQueryShoppingAssistant.h"
#import "GTLServiceShoppingAssistant.h"
