/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantRegistration.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantRegistration (0 custom class methods, 1 custom properties)

#import "GTLShoppingAssistantRegistration.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantRegistration
//

@implementation GTLShoppingAssistantRegistration
@dynamic regId;
@end
