/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantPlace.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantPlace (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLShoppingAssistantGeoPt;

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantPlace
//

@interface GTLShoppingAssistantPlace : GTLObject
@property (copy) NSString *address;
@property (retain) GTLShoppingAssistantGeoPt *location;
@property (copy) NSString *name;
@property (retain) NSNumber *placeId;  // longLongValue
@end
