/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantRegistrationRecord.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantRegistrationRecord (0 custom class methods, 1 custom properties)

#import "GTLShoppingAssistantRegistrationRecord.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantRegistrationRecord
//

@implementation GTLShoppingAssistantRegistrationRecord
@dynamic regId;
@end
