/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API

#import "GTLShoppingAssistantConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeShoppingAssistantUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
