/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShoppingAssistantCheckInCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingAssistantCheckInCollection (0 custom class methods, 1 custom properties)

#import "GTLShoppingAssistantCheckInCollection.h"

#import "GTLShoppingAssistantCheckIn.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingAssistantCheckInCollection
//

@implementation GTLShoppingAssistantCheckInCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLShoppingAssistantCheckIn class]
                                forKey:@"items"];
  return map;
}

@end
