/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLServiceShoppingAssistant.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingAssistant/v1
// Description:
//   This is an API
// Classes:
//   GTLServiceShoppingAssistant (0 custom class methods, 0 custom properties)

#import "GTLShoppingAssistant.h"

@implementation GTLServiceShoppingAssistant

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = [NSArray arrayWithObjects:
                      [GTLQueryShoppingAssistant class],
                      [GTLShoppingAssistantCheckIn class],
                      [GTLShoppingAssistantCheckInCollection class],
                      [GTLShoppingAssistantCollectionResponseRegistration class],
                      [GTLShoppingAssistantGeoPt class],
                      [GTLShoppingAssistantJsonMap class],
                      [GTLShoppingAssistantOffer class],
                      [GTLShoppingAssistantOfferCollection class],
                      [GTLShoppingAssistantPlace class],
                      [GTLShoppingAssistantPlaceInfo class],
                      [GTLShoppingAssistantPlaceInfoCollection class],
                      [GTLShoppingAssistantRecommendation class],
                      [GTLShoppingAssistantRecommendationCollection class],
                      [GTLShoppingAssistantRegistration class],
                      nil];
  return classes;
}
#endif  // DEBUG

- (id)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://{{{YOUR APP ID}}}.appspot.com/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
